name: Python E2E CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask flask_sqlalchemy python-dotenv psycopg2-binary pytest playwright

      - name: Install Playwright browsers
        run: |
          python -m playwright install

      - name: Start Flask app
        run: |
          export FLASK_APP=app.py
          flask run --host=0.0.0.0 &
          sleep 5

      - name: Run Python tests
        env:
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: |
          pytest -v tests/
